var calendarData = new Array();
calendarData.push('{"predmet":"Srpski","month":"3","day":"24","clickUrl":"https://classroom.google.com/u/1/c/NTQ2Mjc5NjY5NDla/p/NjUyOTQ3OTI0MjVa/details","time":"17:00"}');
calendarData.push('{"predmet":"Sociologija","month":"3","day":"25","clickUrl":"https://classroom.google.com/u/1/c/NjI5NDA0MjA4MTda/a/NTQ3OTc2MTc5MDha/details"}');
calendarData.push('{"predmet":"Engleski","month":"3","day":"25","clickUrl":"https://classroom.google.com/u/1/c/NTQ0NDYzMzgyNzBa/a/NjUyNjQzMzEyMzRa/details"}');
calendarData.push('{"predmet":"Mazicka","month":"3","day":"27","clickUrl":"https://classroom.google.com/u/1/c/NTQ2NTk0MzEyNzVa"}');
calendarData.push('{"predmet":"Mreze","month":"3","day":"27","clickUrl":"https://classroom.google.com/u/1/c/NTM4NDAyMTQ1NTla/a/NTU0ODQ3NTQwOTFa/details"}');
calendarData.push('{"predmet":"Operativni","month":"3","day":"30","clickUrl":"https://classroom.google.com/u/1/c/NTQ1Mzk4MDMwOTla/m/NTU0NDAzMDQyMjNa/details"}');
calendarData.push('{"predmet":"Matis","month":"4","day":"3","clickUrl":"https://classroom.google.com/u/1/c/NjEyMjUxMjc3OTla/a/NTUzMjg2MTkwODBa/details"}');
calendarData.push('{"predmet":"Sociologija","month":"4","day":"1","clickUrl":"https://classroom.google.com/u/1/c/NjI5NDA0MjA4MTda/a/NTYxMzM4NDUxNjFa/details"}');
calendarData.push('{"predmet":"Gavanska","month":"3","day":"30","clickUrl":"https://jelenagavanski.gnomio.com/course/view.php?id=4#section-2"}');
calendarData.push('{"predmet":"Srpski","month":"4","day":"2","clickUrl":"https://classroom.google.com/u/1/c/NTQ2Mjc5NjY5NDla/a/NzI5NDA5MzQ1MTha/details"}');
calendarData.push('{"predmet":"Gavanska","month":"4","day":"6","clickUrl":"https://jelenagavanski.gnomio.com/mod/assign/view.php?id=48"}');
calendarData.push('{"predmet":"Operativni","month":"4","day":"1","clickUrl":"https://www.youtube.com/watch?v=dQw4w9WgXcQ"}');
calendarData.push('{"predmet":"Sociologija","month":"4","day":"8","clickUrl":"https://classroom.google.com/u/1/c/NjI5NDA0MjA4MTda/a/NjYwOTM4OTEzMjda/details"}');
calendarData.push('{"predmet":"Engleski","month":"4","day":"8","clickUrl":"https://classroom.google.com/u/1/c/NTQ0NDYzMzgyNzBa/a/NjYxNTg2OTE3MDda/details","time":"14:00"}');
calendarData.push('{"predmet":"Mreze","month":"4","day":"14","clickUrl":"https://classroom.google.com/u/1/c/NTM4NDAyMTQ1NTla/a/NzM2ODkwNzQ5MjBa/details"}');
calendarData.push('{"predmet":"Rakicka","month":"4","day":"3","clickUrl":"https://classroom.google.com/u/1/c/NTM2MzE3ODIyMzda/a/NzQ1NDQwMzY5NDFa/details"}');
calendarData.push('{"predmet":"Srpski","month":"4","day":"8","clickUrl":"https://classroom.google.com/u/1/c/NTQ2Mjc5NjY5NDla/a/NzUwMDUzMzg3Mjda/details","time":"12:00"}');
calendarData.push('{"predmet":"Program","month":"4","day":"10","clickUrl":"https://classroom.google.com/u/1/c/NTM4NDAyMTQ1MTFa/a/NzQ4MDg5NDg1Mjda/details","time":"08:00"}');
calendarData.push('{"predmet":"Rakicka","month":"4","day":"6","clickUrl":"https://classroom.google.com/u/1/c/NTQ1Mzk4MDMwOTla/a/NzQ3ODgyMDA3NTBa/details"}');
calendarData.push('{"predmet":"Mazicka","month":"4","day":"8","clickUrl":"https://classroom.google.com/u/1/c/NTQ2NTk0MzEyNzVa/a/NzQ2OTE4MzQ0NDRa/details"}');
calendarData.push('{"predmet":"Sociologija","month":"4","day":"21","clickUrl":"https://classroom.google.com/u/1/c/NjI5NDA0MjA4MTda/a/NzU1NjY4MjA4ODla/details"}');
calendarData.push('{"predmet":"Gavanska","month":"4","day":"16","clickUrl":"https://jelenagavanski.gnomio.com/mod/assign/view.php?id=75"}');
calendarData.push('{"predmet":"Engleski","month":"4","day":"22","clickUrl":"https://classroom.google.com/u/1/c/NTQ0NDYzMzgyNzBa/a/NjM1OTk5NzU4MDda/details","time":"12:00"}');
calendarData.push('{"predmet":"Program","month":"4","day":"26","clickUrl":"https://classroom.google.com/u/1/c/NTM4NDAyMTQ0NzZa/a/NzY3MDc0MzAxMzha/details"}');
calendarData.push('{"predmet":"Baze","month":"4","day":"24","clickUrl":"https://classroom.google.com/u/1/c/NTM4NjM1ODU3Nzha/a/NzYzODAyNjkwMDVa/details"}');
calendarData.push('{"predmet":"Gavanska","month":"4","day":"20","clickUrl":"https://jelenagavanski.gnomio.com/mod/assign/view.php?id=82"}');
calendarData.push('{"predmet":"Srpski","month":"4","day":"24","clickUrl":"https://classroom.google.com/u/1/c/NTQ2Mjc5NjY5NDla/a/OTI2MTA1NzYzOTRa/details","time":"12:00"}');
calendarData.push('{"predmet":"Sociologija","month":"5","day":"5","clickUrl":"https://classroom.google.com/u/1/c/NjI5NDA0MjA4MTda/a/OTI4OTk0NTcxNzVa/details"}');
calendarData.push('{"predmet":"Engleski","month":"4","day":"29","clickUrl":"https://classroom.google.com/u/1/c/NTQ0NDYzMzgyNzBa/a/OTI4NjkyMjg3ODBa/details"}');
calendarData.push('{"predmet":"Gavanska","month":"4","day":"27","clickUrl":"https://jelenagavanski.gnomio.com/course/view.php?id=4#section-6","time":"12:00"}');
calendarData.push('{"predmet":"Rakicka","month":"4","day":"30","clickUrl":"https://classroom.google.com/u/1/c/NTM2MzE3ODIyMzda/a/Nzk5MzQ0MzI0MjRa/details","time":"12:00"}');

var unknownData = new Array();
unknownData.push('{"predmet":"Ivona","clickUrl":"https://drive.google.com/file/d/1TSIhS_wVBtBFdxE4J1_oVOsGfkcuq6er/view"}');
unknownData.push('{"predmet":"Baze","clickUrl":"https://classroom.google.com/u/1/c/NTM4NjM1ODU3Nzha"}');


var monthData = new Array();
monthData.push('{"prviDan":"3","brojDana":"31"}');
monthData.push('{"prviDan":"6","brojDana":"29"}');
monthData.push('{"prviDan":"7","brojDana":"31"}');
monthData.push('{"prviDan":"3","brojDana":"30"}');
monthData.push('{"prviDan":"5","brojDana":"31"}');
monthData.push('{"prviDan":"1","brojDana":"30"}');
monthData.push('{"prviDan":"3","brojDana":"31"}');
monthData.push('{"prviDan":"6","brojDana":"31"}');
monthData.push('{"prviDan":"2","brojDana":"30"}');
monthData.push('{"prviDan":"4","brojDana":"31"}');
monthData.push('{"prviDan":"7","brojDana":"30"}');
monthData.push('{"prviDan":"2","brojDana":"31"}');